#theme: jekyll-theme-merlot # limited to pre-installed themes by github pages
#remote_theme: jekyll/minima # force to get the theme remotely, in case github's version is old
remote_theme: rahil627/minima-customized # i won't ever rememeber to update my forked version :(

# standard vars
# title: rathewolf # fetches from repo project name
# description: ? # fetches from the repo's about section

# theme vars
minima:
  plugins:
   - jekyll-seo-tag

  skin: solarized #has a book-like texture
  
  author:
    name: rahil627 #does this go to seo?
    
  facebook: rahil627 #where is this?

# custom theme vars
#text-align: inherit #this is a better idea: just set variables from here
footer:
  left: poop.
