#theme: jekyll-theme-merlot # limited to pre-installed themes by github pages
#remote_theme: jekyll/minima # force to get the theme remotely, in case github's version is old
remote_theme: rahil627/minima-custom-jekyll-theme # i won't ever rememeber to update my forked version :(

# standard vars
# title: rathewolf # fetches from repo project name
# description: ? # fetches from the about section of the repo

# theme vars
minima:
  skin: solarized # has a book-like texture
  facebook: rahil627 # where is this?
  
  author:
    name: rahil627 # does this go to seo?

# custom theme vars
footer:
  left: poop.
